name: PostgreSQL Installcheck

on:
  pull_request:
    branches:
      - main

jobs:
  installcheck:
    name: Test ${{ matrix.pg }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 17]
    container: pgxn/pgxn-tools
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: apt-get update && apt-get install -y liblz4-dev libzstd-dev libkrb5-dev
      - name: Start PostgreSQL and install dependencies
        run: |
          pg-start ${{ matrix.pg }}
          make install-dependencies
      - name: Build and test extension
        run: |
          pg-build-test
      - name: Display results
        if: failure()
        run: cat regression.diffs
